config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'posts#index'

  resources :posts
  resources :users

  resources :posts do 
    resources :comments, only: [:create]
  end

  get 'signout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  belongs_to :author, class_name: "User", foreign_key: :author_id
  has_many :comments


end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts, foreign_key: :author_id
	has_many :comments
	has_many :commented_posts, through: :comments, source: :post

	def password
		@password ||= BCrypt::Password.new(password_hash)
	end

	def password=(new_password)
		@password = BCrypt::Password.create(new_password)
		self.password_hash = @password
	end

end

app/controllers/Comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = Comment.new(comment_params)
		@post = Post.find(params[:post_id])
		@comment.post = @post
		@comment.user = current_user
		if @comment.save
			redirect_to @post
		else
			redirect_to @post
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:text)	
	end

end

app/controllers/Posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
		@comment = Comment.new(post: @post)
	end

	def new
		@post = Post.new	
	end

	def create
		@post = Post.new(post_params)
		@post.author = current_user
		if @post.save
			redirect_to @post 
		else
			render "new"
		end
	end

	def edit
		@post = Post.find(params[:id])		
	end

	def update
		@post = Post.find(params[:id])
		@post.update_attributes(post_params)
		if @post.save
			redirect_to @post
		else
			render "edit"
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.delete
		redirect_to current_user
	end

	private

	def post_params
		params.require(:post).permit(:title, :text)
	end

end

app/controllers/Sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.password == params[:password]
			session[:id] = user.id
			redirect_to :root
		else
			render "users/new"
		end
	end

	def destroy
		session[:id] = nil
		redirect_to :root
	end

end

app/controllers/Users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])	
		@posts = @user.posts
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:id] = @user.id
			redirect_to @user 
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find_by(id: session[:id]) if session[:id]
  end

  helper_method :current_user

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
  	@current_user ||= User.find_by(id: session[:id]) if session[:id]
  end


end

app/views/layouts/_navbar.html.erb
<div>
	<%= link_to("ALL BLOGS", :root) %>
	<% if !current_user %>
	<%= link_to("SIGN UP", new_user_path) %>
	<%= link_to("SIGN IN", new_session_path) %>
	<% else %>
	<%= link_to("PROFILE", current_user) %>
	<%= link_to("WRITE A NEW POST", new_post_path) %>
	<%= link_to("SIGN OUT", '/signout') %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render "layouts/navbar" %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :text %>
	<%= f.text_area :text %>
	<%= f.submit "Edit Post" %>
<% end %>

app/views/posts/index.html.erb
<h1>Shiny New Blogs!</h1>
<table>
<% @posts.each do |post| %>
	<tr>
		<td><%= link_to "#{post.title}", post %></td>
		<td><%= link_to "#{post.author.name}", post.author %></td>
	</tr>	
<% end %>	
</table>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :text %>
	<%= f.text_area :text %>
	<%= f.submit "POST" %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h3><%= @post.author.name %></h3>
<p><%= @post.text %></p>
<ul>
	<% @post.comments.each do |comment| %>
		<li><%= comment.text %> - <%= comment.user.name %></li>
	<% end %>
</ul>
 <%= form_for [@post, @comment], action: :post_comments do |f| %>
 <!-- <#%= form_for @comment, url: {action: :post_comments} do |f| %> -->
	<%= f.label :comment %>
	<%= f.text_field :text %>
	<%= f.submit "Leave Comment" %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.submit "Sign Up!" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Posts</h1>
<table>
	<% @posts.each do |post| %>
	<tr>
		<td><%= link_to("#{post.title}", post) %></td>
		<% if @user == current_user %>
			<td><%= link_to("Edit", edit_post_path(post)) %></td>
			<td><%= link_to("Delete", post, method: :delete) %></td>
		<% end %>
	</tr>
	<% end %>
</table>
<h3>Posts on which <%= @user.name %> has commented:</h3>
<ul>
	<% @user.commented_posts.each do |post| %>
	<li><%= link_to("#{post.title}", post_path) %></li>
	<% end %>
</ul>